//
//  Configuration.h
//  DigitalNewzealand
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 06/28/2016
//
#ifndef DigitalNewzealand_Configuration_h
#define DigitalNewzealand_Configuration_h

@interface Configuration : NSObject

/** The base Uri for API calls */
+(NSString*) BaseUri;

/** Your API Key */
+(NSString*) ApiKey;


@end

#endif
